name: Deploy Documentation

on:
  push:
    branches: [ master ]
  # 允许手动触发
  workflow_dispatch:
  # 定期检查 submodule 更新（每天一次）
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  check-submodule:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.check.outputs.updated }}
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 检查 submodule 更新
        id: check
        run: |
          git submodule update --remote --merge
          if git diff --quiet; then
            echo "updated=false" >> $GITHUB_OUTPUT
          else
            echo "updated=true" >> $GITHUB_OUTPUT
          fi

      - name: 提交 submodule 更新
        if: steps.check.outputs.updated == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add framework
          git commit -m "chore: update bevy_framework submodule"
          git push

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: check-submodule
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      needs.check-submodule.outputs.updated == 'true'

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 更新 submodule 到最新
        run: |
          git submodule update --init --recursive
          git submodule update --remote --merge

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 构建文档
        run: npm run docs:build

      - name: 设置 Pages
        uses: actions/configure-pages@v4

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
